### ISSUE TITLE
[BUG] Pypi openapi-generator-cli package has not been updated recently

### ISSUE THREAD

**Issue by RockyMM** [OpenAPITools/openapi-generator-pip#10]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Looking for a Python client generator I realized that the pypi package is very old: https://pypi.org/project/openapi-generator-cli/#description

The description of the package states:

> This project checks the [maven repository](https://mvnrepository.com/artifact/org.openapitools/openapi-generator-cli) once a day for a new version and will publish this new version automatically as a python package.

Obviously, this stopped working back in May 2020.

**Comment by wing328** [comment]
what about using https://www.npmjs.com/package/@openapitools/openapi-generator-cli as a workaround/replacement instead?

understood some people prefer a wrapper CLI in python package but this repo has not been active for years and maintaining a single CLI wrapper in npm seems better for us

**Comment by RockyMM** [comment]
I moved away from the project where I worked with Python. I guess I would be OK with using an npm wrapper. In that case maybe the pypi package should be somehow marked as deprecated.
