### ISSUE TITLE
Add an (extra? optional?) dependency on jdk4py

### ISSUE THREAD

**Issue by ZeeD** [OpenAPITools/openapi-generator-pip#13]
https://pypi.org/project/jdk4py/ offers a way to install the java runtime from pypi.
It would be useful to have it as an optional dependency to avoid runtime errors if no java is installed on the OS

**Comment by eggplants** [comment]
it seems good to run without system installation of java. I will try later.

**Comment by eggplants** [comment]
Looks good.
https://github.com/eggplants/openapi-generator-pip/tree/jdk4py

**Comment by eggplants** [comment]
Looks good. https://github.com/eggplants/openapi-generator-pip/commit/391e1c9976b117dc947d62aadf3c40081856dfb2

**Comment by eggplants** [comment]
It seems that jdk4py is not supported for some environments. For instance, my termux envirnment refuses its installation with poetry.

So I think jdk4py should be kept as optional dependency for now.
