### ISSUE TITLE
Publish old versions

### ISSUE THREAD

**Issue by eggplants** [OpenAPITools/openapi-generator-pip#16]
I would like to publish unpublished versions of cli with release workflow.

**Comment by eggplants** [comment]
For #18, I think 7.10.0 and 4.3.1 have to be re-published as `7.10.0.post0` and `4.3.1.post0`.

**Comment by wing328** [comment]
>  be re-published as 7.10.0.post0 and 4.3.1.post0.

can we avoid that?

can we do it on demand locally in our box (instead of CI) if users ask for an old version?

**Comment by eggplants** [comment]
@wing328 User can specify:
`pip install openapi-generator-cli==7.10.0`

**Comment by wing328** [comment]
ok. thanks for the explanation

i'll leave it up to you on how you would like to proceed

**Comment by eggplants** [comment]
Just published:
- https://pypi.org/project/openapi-generator-cli/4.3.1.post0/
- https://pypi.org/project/openapi-generator-cli/7.10.0.post0/

---

https://pypi.org/project/openapi-generator-cli/#history

![image](https://github.com/user-attachments/assets/7a6b6924-31c6-4aaf-a433-108510e569d2)

**Comment by eggplants** [comment]
Done.
https://github.com/OpenAPITools/openapi-generator-pip/actions/runs/12183546881/job/33985224778

**Comment by wing328** [comment]
looks good according to release history: https://pypi.org/project/openapi-generator-cli/#history

will run some tests tomorrow
