### ISSUE TITLE
PyPI readme has incorrect installation command

### ISSUE THREAD

**Issue by sparrowt** [OpenAPITools/openapi-generator-pip#5]
https://pypi.org/project/openapi-generator-cli/ currently says

> You can install the package either in a virtual environment or globally.
> ```
> # install the latest version of "openapigenerator"
> pip install openapigenerator
> 
> # install a specific version of "openapigenerator"
> pip install openapigenerator==4.2.0
> ```

However that `pip` command doesn't work because it should be `pip install openapi-generator-cli`

Strangely I see that this appears to have been fixed by https://github.com/OpenAPITools/openapi-generator-pip/commit/a1f963e2c376faf536f27d84ba48e0066127c762 so is there something which needs to happen for this to be reflected on PyPI?

**Comment by eggplants** [comment]
https://pypi.org/project/openapi-generator-cli/7.10.0/
