### ISSUE TITLE
Fetch jar during setup or at runtime 

### ISSUE THREAD

**Issue by jayvdb** [OpenAPITools/openapi-generator-pip#6]
When this package is installed as a distro package from the sdist, i.e. https://files.pythonhosted.org/packages/e9/35/cd8615ffa747d006e9d9e8a48744f0bb7a95a418e491cef2714f58c21aa4/openapi-generator-cli-4.3.1.tar.gz, there is no jar.

The error we see is
```
$ openapi-generator generate ...
Error: Unable to access jarfile /usr/lib/python3.10/site-packages/openapi_generator_cli/openapi-generator.jar
```

And there is only one version published on PyPI, 4.3.1, whereas the README says it will publish new versions automatically.

**Comment by eggplants** [comment]
https://pypi.org/project/openapi-generator-cli/7.10.0/ contains jar in the pachage.
