### ISSUE TITLE
Slack invitation link has expired

### ISSUE THREAD

**Issue by eggplants** [OpenAPITools/openapi-generator-pip#9]
Live invitation link: <https://openapi-generator.tech/#:~:text=is%20free%20to-,sign%20up,-.>

Following link has already expired:

https://github.com/OpenAPITools/openapi-generator-pip/blob/91bc8433f974e06fc1201bc23658e2fe8dfab127/README.md?plain=1#L3

**Comment by wing328** [comment]
fixed via https://github.com/OpenAPITools/openapi-generator-pip/commit/29aa7a0a36ce1d0e2f239ba2dbb51d9347733aac

thanks for reporting the issue
